/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { QrCodeService } from "../qrCode.service";
import { QrCodeCreateInput } from "./QrCodeCreateInput";
import { QrCode } from "./QrCode";
import { QrCodeFindManyArgs } from "./QrCodeFindManyArgs";
import { QrCodeWhereUniqueInput } from "./QrCodeWhereUniqueInput";
import { QrCodeUpdateInput } from "./QrCodeUpdateInput";
import { ItemFindManyArgs } from "../../item/base/ItemFindManyArgs";
import { Item } from "../../item/base/Item";
import { ItemWhereUniqueInput } from "../../item/base/ItemWhereUniqueInput";

export class QrCodeControllerBase {
  constructor(protected readonly service: QrCodeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: QrCode })
  async createQrCode(@common.Body() data: QrCodeCreateInput): Promise<QrCode> {
    return await this.service.createQrCode({
      data: {
        ...data,

        item: data.item
          ? {
              connect: data.item,
            }
          : undefined,
      },
      select: {
        code: true,
        createdAt: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [QrCode] })
  @ApiNestedQuery(QrCodeFindManyArgs)
  async qrCodes(@common.Req() request: Request): Promise<QrCode[]> {
    const args = plainToClass(QrCodeFindManyArgs, request.query);
    return this.service.qrCodes({
      ...args,
      select: {
        code: true,
        createdAt: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: QrCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async qrCode(
    @common.Param() params: QrCodeWhereUniqueInput
  ): Promise<QrCode | null> {
    const result = await this.service.qrCode({
      where: params,
      select: {
        code: true,
        createdAt: true,
        id: true,

        item: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: QrCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateQrCode(
    @common.Param() params: QrCodeWhereUniqueInput,
    @common.Body() data: QrCodeUpdateInput
  ): Promise<QrCode | null> {
    try {
      return await this.service.updateQrCode({
        where: params,
        data: {
          ...data,

          item: data.item
            ? {
                connect: data.item,
              }
            : undefined,
        },
        select: {
          code: true,
          createdAt: true,
          id: true,

          item: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: QrCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteQrCode(
    @common.Param() params: QrCodeWhereUniqueInput
  ): Promise<QrCode | null> {
    try {
      return await this.service.deleteQrCode({
        where: params,
        select: {
          code: true,
          createdAt: true,
          id: true,

          item: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/items")
  @ApiNestedQuery(ItemFindManyArgs)
  async findItems(
    @common.Req() request: Request,
    @common.Param() params: QrCodeWhereUniqueInput
  ): Promise<Item[]> {
    const query = plainToClass(ItemFindManyArgs, request.query);
    const results = await this.service.findItems(params.id, {
      ...query,
      select: {
        createdAt: true,
        description: true,
        id: true,
        name: true,

        qrCode: {
          select: {
            id: true,
          },
        },

        status: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/items")
  async connectItems(
    @common.Param() params: QrCodeWhereUniqueInput,
    @common.Body() body: ItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        connect: body,
      },
    };
    await this.service.updateQrCode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/items")
  async updateItems(
    @common.Param() params: QrCodeWhereUniqueInput,
    @common.Body() body: ItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        set: body,
      },
    };
    await this.service.updateQrCode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/items")
  async disconnectItems(
    @common.Param() params: QrCodeWhereUniqueInput,
    @common.Body() body: ItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      items: {
        disconnect: body,
      },
    };
    await this.service.updateQrCode({
      where: params,
      data,
      select: { id: true },
    });
  }
}
