/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { QrCodeWhereUniqueInput } from "../../qrCode/base/QrCodeWhereUniqueInput";
import { QrCodeListRelationFilter } from "../../qrCode/base/QrCodeListRelationFilter";
import { EnumItemStatus } from "./EnumItemStatus";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class ItemWhereInput {
  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => QrCodeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => QrCodeWhereUniqueInput)
  @IsOptional()
  @Field(() => QrCodeWhereUniqueInput, {
    nullable: true,
  })
  qrCode?: QrCodeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => QrCodeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => QrCodeListRelationFilter)
  @IsOptional()
  @Field(() => QrCodeListRelationFilter, {
    nullable: true,
  })
  qrCodes?: QrCodeListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumItemStatus,
  })
  @IsEnum(EnumItemStatus)
  @IsOptional()
  @Field(() => EnumItemStatus, {
    nullable: true,
  })
  status?: "Option1";

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  user?: UserWhereUniqueInput;
}

export { ItemWhereInput as ItemWhereInput };
